name: 'setup-wiz'
description: 'Setup wiz language'
author: 'ChanTsune'
inputs:
  version:
    description: 'The install version of wiz. The latest version of wiz will install with the default.'
    required: false
    default: ''
  uninstall:
    description: 'Uninstall wiz in post process'
    required: false
    default: false
outputs:
  path:
    description: 'The path of wiz installed'
  version:
    description: 'The version of installed wiz'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
