name: 'setup-wiz'
description: 'Setup wiz language'
author: 'ChanTsune'

outputs:
  path:
    description: 'The path of wiz installed'
  version:
    description: 'The version of installed wiz'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
