name: "Build and commit"

on:
  push:
    branches:
      - main
jobs: 
  run:
    name: "Build and commit"
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Update source code
      run: npm run build && npm run package

    - id: get_email
      name: get auther email
      run: echo "::set-output name=auther_email::$(git log -n 1 --format='%ce')"

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: "${{ steps.get_email.outputs.auther_email }}"
        message: "build commit"
        add: "dist/*.js"
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
